---
title: "figures_and_tables"
output: html_document
date: "2024-04-03"
editor_options: 
  chunk_output_type: inline
  markdown: 
    wrap: 72
---

# Library

```{r}
library(tidyverse)
library(googlesheets4)
library(oce)
library(padr)
library(rEDM)
library(ggplot2)
library(zoo)
library(quantreg)
library(dplyr)
library(forecast)
#test

```


# PRELIM STATS 

#FIND CRITICAL VALUES

```{r}
critical.r <- function( n, alpha = .05 ) {
  df <- n - 2
  critical.t <- qt(alpha/2, df, lower.tail = F)
  critical.r <- sqrt( (critical.t^2) / ( (critical.t^2) + df ) )
  return(critical.r)
}
# Example usage: Critical correlation coefficient at sample size of n = 100
critical.r( 100 )


if (file.exists("critical.r .rds")) {
  # If it's saved locally, load the data
  critical.r <- readRDS("critical.r.rds")
} else {
  # If it's not saved locally, read it from Google Sheets and save it locally
  saveRDS(critical.r , "critical.r .rds")
}

```


#TABLE AG_DF_CR

```{r}
# Assuming 'ag_df_CR' is your data frame

# Create an empty list to store the results
lm_list <- list()

# List of variables to include in the linear models
vars <- c("ph", "Celsius", "spcond", "do", "turb", "Salinity")

# Iterate over each variable
for (var in vars) {
  # Create the formula for the linear model
  formula_chl <- paste("chl ~", var)
  formula_phy <- paste("phy ~", var)
  
  # Fit the linear model for 'chl'
  lm_chl <- lm(formula_chl, data = ag_df_CR)
  # Fit the linear model for 'phy'
  lm_phy <- lm(formula_phy, data = ag_df_CR)
  
  # Store the results in the list
  lm_list[[paste(var, "chl", sep = "_")]] <- lm_chl
  lm_list[[paste(var, "phy", sep = "_")]] <- lm_phy
}

```

```{r}
# Create an empty data frame to store the results
results_df <- data.frame(variable = character(), response = character(), 
                          correlation = numeric(), r_squared = numeric(), p_value = numeric(), critical_correlation = numeric(),
                          stringsAsFactors = FALSE)

# Iterate over each variable
for (var in vars) {
  # Create the formula for the linear model
  formula_chl <- paste("chl ~", var)
  formula_phy <- paste("phy ~", var)
  
  # Fit the linear model for 'chl'
  lm_chl <- lm(formula_chl, data = ag_df_CR)
  # Fit the linear model for 'phy'
  lm_phy <- lm(formula_phy, data = ag_df_CR)
  
  # Extract correlation coefficient, R-squared value, p-value
  cor_chl <- cor(ag_df_CR[[var]], ag_df_CR$chl)
  cor_phy <- cor(ag_df_CR[[var]], ag_df_CR$phy)
  r_squared_chl <- summary(lm_chl)$r.squared
  r_squared_phy <- summary(lm_phy)$r.squared
  p_value_chl <- summary(lm_chl)$coefficients[2, 4]
  p_value_phy <- summary(lm_phy)$coefficients[2, 4]
  
  #critical corr sample size
  
  critical_r_chl <- critical.r(length(ag_df_CR$chl))
  critical_r_phy <- critical.r(length(ag_df_CR$phy))
  
  
  # Add the results to the data frame
  results_df <- rbind(results_df, 
                      data.frame(variable = var, response = "chl",  
                                 correlation = cor_chl, r_squared = r_squared_chl, p_value = p_value_chl),
                      data.frame(variable = var, response = "phy",
                                 correlation = cor_phy, r_squared = r_squared_phy, p_value = p_value_phy))
}

results_df$Significance <- ifelse(
  (results_df$response == "chl" & abs(results_df$correlation) >=   critical_r_chl) |
  (results_df$response == "phy" & abs(results_df$correlation) >=  critical_r_phy),
  "Significant",
  "Not Significant"
)


# Print the results
print(results_df)


```

#ARIMA

#ARIMA 9-12 CHL

```{r}
morndf_CR <- morndf_CR %>% pad()

class(morndf_CR )
morndf_CR$chl <- as.numeric(morndf_CR$chl)

#plot(ag_morndf_CR$date, ag_morndf$chl) 

#Fit Dataset
rate <- ts(morndf_CR [,'chl'],start = c(2015,5), frequency = 365 )
#Tell the gaps and days 


#Grab Data
autoplot(rate) + ggtitle ("Autoplot - Non-Aggregated ") + ylab("Chlorophyll (RFU)") + theme(plot.title = element_text(hjust = 0.5))



#Build ARIMA Model - include seasonal autoregressive and seasonal autoregressive moving averages.
fit_ARIMA_morndf_CR_chl <-auto.arima(rate, seasonal = TRUE)
print(summary(fit_ARIMA_morndf_CR_chl))
checkresiduals(fit_ARIMA_morndf_CR_chl)


#Forecast
fcast <- forecast(fit_ARIMA_morndf_CR_chl, h =365) #h = amount of periods ahead
autoplot
plot(fcast)
print(summary(fcast))

#Fitting an auto.arima model in R using the Forecast package
#fit_basic1<- auto.arima(morndf_CR,xreg=trainREG_TS)
#forecast_1<-forecast(fit_basic1,xreg = testREG_TS)

ARIMA_morndf_chl <- saveRDS(fcast, file = "ARIMA_morndf_chl")

```


#ARIMA 9-12 PHY

```{r}
morndf_CR <- morndf_CR %>% pad()

class(morndf_CR )
morndf_CR$phy <- as.numeric(morndf_CR$phy)

#plot(ag_morndf_CR$date, ag_morndf_CR$chl) 

#Fit Dataset
rate <- ts(morndf_CR [,'phy'],start = c(2015,5), frequency = 365 )
#Tell the gaps and days 


#Grab Data
autoplot(rate) + ggtitle ("Autoplot - Non-Aggregated ") + ylab("Phycocanin (RFU)") + theme(plot.title = element_text(hjust = 0.5))



#Build ARIMA Model - include seasonal autoregressive and seasonal autoregressive moving averages.
fit_ARIMA_morndf_phy <-auto.arima(rate, seasonal = TRUE)
print(summary(fit_ARIMA_morndf_phy))
checkresiduals(fit_ARIMA_morndf_phy)


#Forecast
fcast <- forecast(fit_ARIMA_morndf_phy, h =365) #h = amount of periods ahead
autoplot
plot(fcast)
print(summary(fcast))

#Fitting an auto.arima model in R using the Forecast package
#fit_basic1<- auto.arima(morndf_CR,xreg=trainREG_TS)
#forecast_1<-forecast(fit_basic1,xreg = testREG_TS)

ARIMA_morndf_phy <- saveRDS(fcast, file = "ARIMA_morndf_phy")


```


## ARIMA Non-Aggregated CHL

```{r}
df_CR <- df_CR %>% pad()

class(df_CR )
df_CR $chl <- as.numeric(df_CR$chl)

#plot(ag_df_CR$date, ag_df_CR$chl) 

#Fit Dataset
rate <- ts(df_CR [,'chl'],start = c(2015,5), frequency = 365 )
#Tell the gaps and days 


#Grab Data
autoplot(rate) + ggtitle ("Autoplot - Non-Aggregated ") + ylab("Chlorophyll (RFU)") + theme(plot.title = element_text(hjust = 0.5))



#Build ARIMA Model - include seasonal autoregressive and seasonal autoregressive moving averages.
fit_ARIMA_df_chl <-auto.arima(rate, seasonal = TRUE)
print(summary(fit_ARIMA_df_chl))
checkresiduals(fit_ARIMA_df_chl)


#Forecast
fcast <- forecast(fit_ARIMA_df_chl, h =365) #h = amount of periods ahead
autoplot
plot(fcast)
print(summary(fcast))

#Fitting an auto.arima model in R using the Forecast package
#fit_basic1<- auto.arima(df_CR,xreg=trainREG_TS)
#forecast_1<-forecast(fit_basic1,xreg = testREG_TS)

ARIMA_df_chl <- saveRDS(fcast, file = "ARIMA_df_chl")


```

## ARIMA Non-Aggregated PHY


```{r}
df_CR <- df_CR %>% pad()

class(df_CR )
df_CR $phy <- as.numeric(df_CR$phy)

#plot(ag_df_CR$date, ag_df_CR$chl) 

#Fit Dataset
rate <- ts(df_CR [,'phy'],start = c(2015,5), frequency = 365 )
#Tell the gaps and days 


#Grab Data
autoplot(rate) + ggtitle ("Autoplot - Non-Aggregated ") + ylab("Phycocanin (RFU)") + theme(plot.title = element_text(hjust = 0.5))



#Build ARIMA Model - include seasonal autoregressive and seasonal autoregressive moving averages.
fit_ARIMA_df_phy <-auto.arima(rate, seasonal = TRUE)
print(summary(fit_ARIMA_df_phy))
checkresiduals(fit_ARIMA_df_phy)


#Forecast
fcast <- forecast(fit_ARIMA_df_phy, h =365) #h = amount of periods ahead
autoplot
plot(fcast)
print(summary(fcast))


ARIMA_df_phy <- saveRDS(fcast, file = "ARIMA_df_phy")


```

## ARIMA Aggreggated Daily CHL

```{r}
ag_df_CR <- ag_df_CR  %>% pad()
ag_df_CR$phy <- as.numeric(ag_df_CR$phy)


class(ag_df_CR)
ag_df_CR$chl <- as.numeric(ag_df_CR$chl)

##CHL


#Fit Dataset
rate <- ts(ag_df_CR[,'chl'],start = c(2015,5), frequency = 365 )
#Tell the gaps and days 



#Grab Data
autoplot(rate) + ggtitle ("Autoplot - Daily Aggregate ") + ylab("Chlorophyll (RFU)") + theme(plot.title = element_text(hjust = 0.5))


#Build ARIMA Model - include seasonal autoregressive and seasonal autoregressive moving averages.
fit_ARIMA_ag_chl <-auto.arima(rate, seasonal = TRUE)
print(summary(fit_ARIMA_ag_chl))
checkresiduals(fit_ARIMA_ag_chl)


#Forecast
fcast <- forecast(fit_ARIMA_ag_chl, h =365) #h = amount of periods ahead
autoplot
plot(fcast)
print(summary(fcast))

#Fitting an auto.arima model in R using the Forecast package
#fit_basic1<- auto.arima(df_CR,xreg=trainREG_TS)
#forecast_1<-forecast(fit_basic1,xreg = testREG_TS)

ARIMA_ag_df_phy <- saveRDS(fcast, file = "ARIMA_ag_df_chl")


#fcast$mean

ARIMA_ag_df_phy_pred <- data.frame(fcast$mean)
print(ARIMA_ag_df_phy_pred)


colnames(ARIMA_ag_df_phy_pred) <- "forecast_phy"

# Create date sequence starting from the 172nd day of 2023
start_date <- as.Date("2023-01-01") + 171  # 172nd day = 171 days after Jan 1
num_days <- nrow(ARIMA_ag_df_phy_pred)

ARIMA_ag_df_phy_pred$date <- seq(from = start_date, by = "day", length.out = num_days)

# Print result
print(ARIMA_ag_df_phy_pred)

all_ARIMA_ag_df_phy_pred <- left_join(ag_df_CR, ARIMA_ag_df_phy_pred, by = "date")

all_ARIMA_ag_df_phy_pred <- na.omit(all_ARIMA_ag_df_phy_pred)

ARIMA_ag_df_phy_pred_results <- ComputeError(all_ARIMA_ag_df_phy_pred$phy, all_ARIMA_ag_df_phy_pred$forecast_phy )

ARIMA_ag_df_phy_pred_results$rho

```

## ARIMA Aggreggated Daily PHY
```{r}

##PHY

ag_df_CR <- ag_df_CR  %>% pad()
ag_df_CR$phy <- as.numeric(ag_df_CR$phy)


#Fit Dataset
rate <- ts(ag_df_CR[,'phy'],start = c(2015,5), frequency = 365 )
#Tell the gaps and days 



#Grab Data
autoplot(rate) + ggtitle ("ARIMA - Daily Aggregate ") + ylab("Phycocanin (RFU)") + theme(plot.title = element_text(hjust = 0.5))



#Build ARIMA Model - include seasonal autoregressive and seasonal autoregressive moving averages.
fit_ARIMA_ag_phy <-auto.arima(rate, seasonal = TRUE)
print(summary(fit_ARIMA_ag_phy))
checkresiduals(fit_ARIMA_ag_phy)


#Forecast
fcast <- forecast(fit_ARIMA_ag_phy, h =365) #h = amount of periods ahead
autoplot
plot(fcast)
print(summary(fcast))

#Fitting an auto.arima model in R using the Forecast package
#fit_basic1<- auto.arima(df_CR,xreg=trainREG_TS)
#forecast_1<-forecast(fit_basic1,xreg = testREG_TS)


ARIMA_ag_df_phy <- saveRDS(fcast, file = "ARIMA_ag_df_phy")


fcast

```




#Export 
```{r}


# Install necessary packages if not already installed
if (!requireNamespace("gridExtra", quietly = TRUE)) install.packages("gridExtra")
if (!requireNamespace("grid", quietly = TRUE)) install.packages("grid")

# Load required libraries
library(gridExtra)
library(grid)

# Define output file path
output_file <- "results_df.png"

# Open PNG graphics device
png(output_file, width = 1200, height = 600, res = 150)  # Adjust size & resolution

# Create table and plot
grid.newpage()
grid.table(results_df)

# Close the graphics device
dev.off()


```

#Histogram

```{r}
ARIMA_ag_df_phy_pred_results$rho






```

